version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./mysql.env
    volumes:
      - ./data:/var/lib/mysql
