version: "3"

services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    ports:
      - "25565:25565/tcp"
    env_file:
      ./minecraft.env
    volumes:
      - ./data:/data