version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./mongodb.env
    volumes:
      - ./data:/data/db
